##### generate from dotfile #####

# user alias
alias mongo="mongo ${HOME}/.mongorc.js --shell"
alias toutf8="nkf -w --overwrite ${1}"
alias rm='rmtrash'
alias ll="ls -lh"
alias la="ls -lha"
alias cd..="cd .."
function fname() {
    echo "arguments: ${1}, ${2}"
    find ${1} -name ${2}
}

export EDITOR="subl"
export JAVA_HOME="/Library/Java/home"
export HADOOP_HOME="/usr/local/Cellar/hadoop/*/"
export MAHOUT_HOME="/usr/local/Cellar/mahout/*/"

#homebrew cask
export HOMEBREW_CASK_OPTS="--appdir=/Applications --caskroom=/usr/local/Caskroom"

# git completion
source /Library/Developer/CommandLineTools/usr/share/git-core/git-prompt.sh
source /Library/Developer/CommandLineTools/usr/share/git-core/git-completion.bash
GIT_PS1_SHOWDIRTYSTATE=true
export PS1='\[\033[32m\]\h\[\033[00m\]:\[\033[34m\]\W\[\033[31m\]$(__git_ps1)\[\033[00m\]\$ '

# mahout
MAHOUT_HOME=/usr/local/Cellar/mahout/0.8

# npm
export PATH=/usr/local/lib/node_modules:$PATH

# for Cairo(dependency of node_module of canvas)
export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/opt/X11/lib/pkgconfig

export PATH="$HOME/.bin:${PATH}"

##### end #####
