# bash-completion
if [ -f $(brew --prefix)/etc/bash_completion ]; then
    . $(brew --prefix)/etc/bash_completion
fi

# user alias
alias toutf8="nkf -w --overwrite ${1}"
alias rm='rmtrash'
alias ls="ls -G"
alias ll="ls -lhFG"
alias la="ls -lhaG"
alias cd..="cd .."
alias grep="grep --with-filename --line-number --color=always -R"
alias ag="ag --color"
alias less="less -R"
function fname() {
    echo "arguments: ${1}, ${2}"
    find ${1} -name ${2}
}

# direnv
eval "$(direnv hook $0)"

# git completion
source ${HOME}/.git-prompt.sh
source ${HOME}/.git-completion.bash
GIT_PS1_SHOWDIRTYSTATE=true
export PS1='\[\033[32m\]\h\[\033[00m\]:\[\033[34m\]\W\[\033[31m\]$(__git_ps1)\[\033[00m\]\$ '
