##### generate from dotfile #####
# bash-completion
if [ -f $(brew --prefix)/etc/bash_completion ]; then
    . $(brew --prefix)/etc/bash_completion
fi

# user alias
alias mongo="mongo ${HOME}/.mongorc.js --shell"
alias toutf8="nkf -w --overwrite ${1}"
alias rm='rmtrash'
alias ls="ls -G"
alias ll="ls -lhFG"
alias la="ls -lhaG"
alias rmr="rm -r"
alias cd..="cd .."
alias grep="grep --with-filename --line-number --color=always -R"
alias ag="ag --color"
alias less="less -R"
alias desk="cd ~/Desktop"
alias f="open ."
dic () {
  w3m "http://ejje.weblio.jp/content/$1" | grep "用例"
}
fname() {
    echo "arguments: ${1}, ${2}"
    find ${1} -name ${2}
}
# peco C-r history search
peco-select-history() {
    declare l=$(HISTTIMEFORMAT= history | sort -k1,1nr | perl -ne 'BEGIN { my @lines = (); } s/^\s*\d+\s*//; $in=$_; if (!(grep {$in eq $_} @lines)) { push(@lines, $in); print $in; }' | peco --query "$READLINE_LINE")
    READLINE_LINE="$l"
    READLINE_POINT=${#l}
}
bind -x '"\C-r": peco-select-history'

# direnv
eval "$(direnv hook $0)"

# git completion
source ~/.git/git-prompt.sh
source ~/.git/git-completion.bash
GIT_PS1_SHOWDIRTYSTATE=true
export PS1='\[\033[32m\]\h\[\033[00m\]:\[\033[34m\]\W\[\033[31m\]$(__git_ps1)\[\033[00m\]\$ '

##### end #####
